// for generate go code
// at repository root, execute 'protoc -I="." --go_out=. ./*.proto'

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.1
// source: np2p_packet.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Np2PPacketPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*Np2PEventPB `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Reqs   []*Np2PReqPB   `protobuf:"bytes,2,rep,name=reqs,proto3" json:"reqs,omitempty"`
}

func (x *Np2PPacketPB) Reset() {
	*x = Np2PPacketPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_np2p_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Np2PPacketPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Np2PPacketPB) ProtoMessage() {}

func (x *Np2PPacketPB) ProtoReflect() protoreflect.Message {
	mi := &file_np2p_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Np2PPacketPB.ProtoReflect.Descriptor instead.
func (*Np2PPacketPB) Descriptor() ([]byte, []int) {
	return file_np2p_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Np2PPacketPB) GetEvents() []*Np2PEventPB {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Np2PPacketPB) GetReqs() []*Np2PReqPB {
	if x != nil {
		return x.Reqs
	}
	return nil
}

var File_np2p_packet_proto protoreflect.FileDescriptor

var file_np2p_packet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6e, 0x70, 0x32, 0x70, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x10, 0x6e, 0x70, 0x32,
	0x70, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6e,
	0x70, 0x32, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a,
	0x0c, 0x4e, 0x70, 0x32, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x42, 0x12, 0x2b, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4e, 0x70, 0x32, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x50, 0x42, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x65,
	0x71, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2e, 0x4e, 0x70, 0x32, 0x70, 0x52, 0x65, 0x71, 0x50, 0x42, 0x52, 0x04, 0x72, 0x65, 0x71,
	0x73, 0x42, 0x09, 0x5a, 0x07, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_np2p_packet_proto_rawDescOnce sync.Once
	file_np2p_packet_proto_rawDescData = file_np2p_packet_proto_rawDesc
)

func file_np2p_packet_proto_rawDescGZIP() []byte {
	file_np2p_packet_proto_rawDescOnce.Do(func() {
		file_np2p_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_np2p_packet_proto_rawDescData)
	})
	return file_np2p_packet_proto_rawDescData
}

var file_np2p_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_np2p_packet_proto_goTypes = []interface{}{
	(*Np2PPacketPB)(nil), // 0: schema.Np2pPacketPB
	(*Np2PEventPB)(nil),  // 1: schema.Np2pEventPB
	(*Np2PReqPB)(nil),    // 2: schema.Np2pReqPB
}
var file_np2p_packet_proto_depIdxs = []int32{
	1, // 0: schema.Np2pPacketPB.events:type_name -> schema.Np2pEventPB
	2, // 1: schema.Np2pPacketPB.reqs:type_name -> schema.Np2pReqPB
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_np2p_packet_proto_init() }
func file_np2p_packet_proto_init() {
	if File_np2p_packet_proto != nil {
		return
	}
	file_np2p_event_proto_init()
	file_np2p_req_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_np2p_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Np2PPacketPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_np2p_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_np2p_packet_proto_goTypes,
		DependencyIndexes: file_np2p_packet_proto_depIdxs,
		MessageInfos:      file_np2p_packet_proto_msgTypes,
	}.Build()
	File_np2p_packet_proto = out.File
	file_np2p_packet_proto_rawDesc = nil
	file_np2p_packet_proto_goTypes = nil
	file_np2p_packet_proto_depIdxs = nil
}
